### ISSUE TITLE
Header / Footer einfügen

### ISSUE THREAD

**Issue by LorenzKuehl** [coding-bootcamps-eu/final-project-2023-12-carma#21]
Um das layout einheitlich zu halten, sollte das nav-menu in ein header-tag, bzw. der "carma"-Schriftzug in ein footer-tag. Abwarten bis alle views gepusht sind, um es dann einheitlich zu machen. **Zeitpunkt und Vorgehen noch einmal gemeinsam abstimmen!**

**Comment by dorojuse** [comment]
Wir machen nur einen header und footer in der App.vue, daher brauchen wir das nicht mehr!
